### ISSUE TITLE
[BUG][run/serve project] - cannot start project

### ISSUE THREAD

**Issue by devzom** [LouisMazel/maz-ui#222]
**Describe the bug**

There's an issue with starting docs project.

**To Reproduce**

1. Follow [contributing guidelines](https://github.com/LouisMazel/maz-ui/blob/a3ce02be3fa7a75a99abbdae7022ccf810adb1b4/.github/CONTRIBUTING.md)
2. See error:

```bash
make install
...
make serve
make --directory=packages/docs serve
npm run docs:dev

> docs@3.0.0-next.14 docs:dev
> vuepress dev docs

warning plugin @vuepress/plugin-medium-zoom has been used multiple times, only the last one will take effect
info Initializing VuePress and preparing data...
✘ [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "maz-ui". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "maz-ui". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:10:
      29537 │     throw new Error(`Failed to resolve entry for package "${id}". ` +
            ╵           ^

    at packageEntryFailure (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:11)
    at resolvePackageEntry (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:29533:9)
    at tryNodeResolve (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:29349:20)
    at Context.resolveId (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:29166:28)
    at Object.resolveId (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38271:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38474:26)
    at async /Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38612:34
    at async callback (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:917:28)
    at async handleRequest (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:697:30)

  This error came from the "onResolve" callback registered here:

    node_modules/vite/dist/node/chunks/dep-9c153816.js:38602:18:
      38602 │             build.onResolve({
            ╵                   ~~~~~~~~~

    at setup (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38602:19)
    at handlePlugins (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:839:23)
    at Object.buildOrServe (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:1133:7)
    at /Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:2074:17
    at new Promise (<anonymous>)
    at Object.build (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:2073:14)
    at Object.build (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:1923:51)
    at /Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38432:54
    at Array.map (<anonymous>)

  The plugin "vite:dep-scan" was triggered by this import

    html:/Users/admin/dev/contribute/maz-ui/packages/docs/docs/.vuepress/.temp/pages/filters/capitalize.html.vue:2:29:
      2 │   import { capitalize } from 'maz-ui'
        ╵                              ~~~~~~~~

✘ [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "maz-ui". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "maz-ui". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:10:
      29537 │     throw new Error(`Failed to resolve entry for package "${id}". ` +
            ╵           ^

    at packageEntryFailure (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:11)
    at resolvePackageEntry (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:29533:9)
    at tryNodeResolve (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:29349:20)
    at Context.resolveId (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:29166:28)
    at Object.resolveId (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38271:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38474:26)
    at async /Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38612:34
    at async callback (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:917:28)
    at async handleRequest (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:697:30)

  This error came from the "onResolve" callback registered here:

    node_modules/vite/dist/node/chunks/dep-9c153816.js:38602:18:
      38602 │             build.onResolve({
            ╵                   ~~~~~~~~~

    at setup (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38602:19)
    at handlePlugins (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:839:23)
    at Object.buildOrServe (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:1133:7)
    at /Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:2074:17
    at new Promise (<anonymous>)
    at Object.build (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:2073:14)
    at Object.build (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:1923:51)
    at /Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38432:54
    at Array.map (<anonymous>)

  The plugin "vite:dep-scan" was triggered by this import

    html:/Users/admin/dev/contribute/maz-ui/packages/docs/docs/.vuepress/.temp/pages/filters/number.html.vue:2:25:
      2 │   import { number } from 'maz-ui'
        ╵                          ~~~~~~~~

✘ [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "maz-ui". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "maz-ui". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:10:
      29537 │     throw new Error(`Failed to resolve entry for package "${id}". ` +
            ╵           ^

    at packageEntryFailure (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:11)
    at resolvePackageEntry (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:29533:9)
    at tryNodeResolve (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:29349:20)
    at Context.resolveId (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:29166:28)
    at Object.resolveId (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38271:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38474:26)
    at async /Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38612:34
    at async callback (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:917:28)
    at async handleRequest (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:697:30)

  This error came from the "onResolve" callback registered here:

    node_modules/vite/dist/node/chunks/dep-9c153816.js:38602:18:
      38602 │             build.onResolve({
            ╵                   ~~~~~~~~~

    at setup (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38602:19)
    at handlePlugins (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:839:23)
    at Object.buildOrServe (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:1133:7)
    at /Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:2074:17
    at new Promise (<anonymous>)
    at Object.build (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:2073:14)
    at Object.build (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:1923:51)
    at /Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38432:54
    at Array.map (<anonymous>)

  The plugin "vite:dep-scan" was triggered by this import

    html:/Users/admin/dev/contribute/maz-ui/packages/docs/docs/.vuepress/.temp/pages/filters/date.html.vue:2:23:
      2 │   import { date } from 'maz-ui'
        ╵                        ~~~~~~~~

✘ [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "maz-ui". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "maz-ui". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:10:
      29537 │     throw new Error(`Failed to resolve entry for package "${id}". ` +
            ╵           ^

    at packageEntryFailure (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:11)
    at resolvePackageEntry (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:29533:9)
    at tryNodeResolve (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:29349:20)
    at Context.resolveId (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:29166:28)
    at Object.resolveId (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38271:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38474:26)
    at async /Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38612:34
    at async callback (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:917:28)
    at async handleRequest (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:697:30)

  This error came from the "onResolve" callback registered here:

    node_modules/vite/dist/node/chunks/dep-9c153816.js:38602:18:
      38602 │             build.onResolve({
            ╵                   ~~~~~~~~~

    at setup (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38602:19)
    at handlePlugins (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:839:23)
    at Object.buildOrServe (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:1133:7)
    at /Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:2074:17
    at new Promise (<anonymous>)
    at Object.build (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:2073:14)
    at Object.build (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:1923:51)
    at /Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/dist/node/chunks/dep-9c153816.js:38432:54
    at Array.map (<anonymous>)

  The plugin "vite:dep-scan" was triggered by this import

    html:/Users/admin/dev/contribute/maz-ui/packages/docs/docs/.vuepress/.temp/pages/filters/currency.html.vue:2:27:
      2 │   import { currency } from 'maz-ui'
        ╵                            ~~~~~~~~

Error: Build failed with 4 errors:
node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:10: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "maz-ui". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "maz-ui". The package may have incorrect main/module/exports specified in its package.json.
node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:10: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "maz-ui". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "maz-ui". The package may have incorrect main/module/exports specified in its package.json.
node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:10: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "maz-ui". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "maz-ui". The package may have incorrect main/module/exports specified in its package.json.
node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:10: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "maz-ui". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "maz-ui". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:1599:15)
    at /Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:1245:28
    at runOnEndCallbacks (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:1030:63)
    at buildResponseToResult (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:1243:7)
    at /Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:1352:14
    at /Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:662:9
    at handleIncomingPacket (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:759:9)
    at Socket.readFromStdout (/Users/admin/dev/contribute/maz-ui/packages/docs/node_modules/vite/node_modules/esbuild/lib/main.js:629:7)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
make[1]: *** [serve] Error 1
make: *** [serve] Error 2
```

**Expected behavior**

Documentation project should start without any problems.

- OS: [MacOS]
- Node [14.19.0]
- NPM [8.5.4]

**Comment by LouisMazel** [comment]
@devzom 

The documentation about the contribution for the `next` version was not up to date, I just updated it.

- [CONTRIBUTING.md](https://github.com/LouisMazel/maz-ui/blob/next/.github/CONTRIBUTING.md)

If you have any question, don't hesitate to ask me :)

Thank you !

**Comment by devzom** [comment]
Okey! great that it's a such a small issue then :) thanks for quick response, I want to contribute :)
