### ISSUE TITLE
[BUG](MazAccordion) Auto import fail with nuxt-module

### ISSUE THREAD

**Issue by sohilpro** [LouisMazel/maz-ui#928]
maz accordion when using this error in nuxt

``` javascript
Could not resolve "chart.js" imported by "maz-ui". Is it installed?

at ViteNodeRunner.runModule (/C:/Users/sohilpro/Desktop/eram-service/eram-front/node_modules/vite-node/dist/client.mjs:362:11)
at ViteNodeRunner.directRequest (/C:/Users/sohilpro/Desktop/eram-service/eram-front/node_modules/vite-node/dist/client.mjs:346:16)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ViteNodeRunner.cachedRequest (/C:/Users/sohilpro/Desktop/eram-service/eram-front/node_modules/vite-node/dist/client.mjs:189:14)
at async ViteNodeRunner.dependencyRequest (/C:/Users/sohilpro/Desktop/eram-service/eram-front/node_modules/vite-node/dist/client.mjs:233:12)
at async C:\Users\sohilpro\Desktop\eram-service\eram-front\node_modules\maz-ui\components\chunks\MazAccordion-3KSb_aBw.mjs:3:31
at async ViteNodeRunner.runModule (/C:/Users/sohilpro/Desktop/eram-service/eram-front/node_modules/vite-node/dist/client.mjs:362:5)
at async ViteNodeRunner.directRequest (/C:/Users/sohilpro/Desktop/eram-service/eram-front/node_modules/vite-node/dist/client.mjs:346:5)
at async ViteNodeRunner.cachedRequest (/C:/Users/sohilpro/Desktop/eram-service/eram-front/node_modules/vite-node/dist/client.mjs:189:14)
```

**Comment by LouisMazel** [comment]
Hi,

Can you share me your code? 
How do you import the component? 

You should import the component like this:

```ts
import MazAccordion from 'maz-ui/components/MazAccordion'
```

**Comment by LouisMazel** [comment]
@sohilpro Can you share me a reproduction link or your code please ?

**Comment by LouisMazel** [comment]
I tested it with stackblitz, I don't have any bug

https://stackblitz.com/edit/nuxt-starter-smrupt?file=app.vue
